apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-docs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : odocs-server
    spec:
      containers:
        - name: odocs-server
          image: satyamz/mdocs:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: odocs-service
  name: openebs-docs-service
spec:
  type: NodePort
  ports:
  - name: odocs-server
    port: 3000
    nodePort: 30551
    protocol: TCP
  selector:
    app: odocs-server

